# Generated by Django 4.0.4 on 2022-06-07 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Home_Address', models.CharField(max_length=10000)),
                ('Vacation_Address', models.CharField(max_length=10000)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='information.people')),
            ],
        ),
    ]
