# Generated by Django 4.0.4 on 2022-06-07 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0002_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=10000)),
                ('Last_Name', models.CharField(max_length=10000)),
                ('Name_Of_Patient', models.ManyToManyField(to='information.people')),
            ],
        ),
    ]
