# Generated by Django 4.0.4 on 2022-06-07 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0003_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('About_Yourself', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='information.people')),
            ],
        ),
    ]
