# Generated by Django 4.0.4 on 2022-06-07 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0004_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Name', models.CharField(max_length=10000)),
                ('Product_Price', models.CharField(max_length=10000)),
            ],
        ),
    ]
