# Generated by Django 4.0.4 on 2022-06-07 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0005_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bio',
            old_name='About_Yourself',
            new_name='About',
        ),
        migrations.AddField(
            model_name='bio',
            name='Add_Bio',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
